roles/lnls-ans-role-sirius-apps/tasks/clone-install-app.yml
Fix installations of repositories where a subdirectory should be installed, instead of the root directory.
=> Small bug fix.

hosts
- until dhcp/dns resolution is fixed
=> Use IPs instead of hostnames for fac servers

group_vars/all, roles/lnls-ans-role-octave/.flake8, roles/lnls-ans-role-octave/.gitignore, roles/lnls-ans-role-octave/.yamllint, roles/lnls-ans-role-octave/LICENSE, roles/lnls-ans-role-octave/README.md, roles/lnls-ans-role-octave/defaults/main.yml, roles/lnls-ans-role-octave/meta/main.yml, roles/lnls-ans-role-octave/molecule/default/Dockerfile.j2, roles/lnls-ans-role-octave/molecule/default/README.md, roles/lnls-ans-role-octave/molecule/default/create.yml, roles/lnls-ans-role-octave/molecule/default/destroy.yml, roles/lnls-ans-role-octave/molecule/default/molecule.yml, roles/lnls-ans-role-octave/molecule/default/playbook.yml, roles/lnls-ans-role-octave/molecule/default/tests/test_default.py, roles/lnls-ans-role-octave/tasks/main.yml, roles/lnls-ans-role-octave/tasks/setup-Debian.yml, roles/lnls-ans-role-octave/tasks/setup-RedHat.yml, roles/lnls-ans-role-octave/vars/Debian-buster.yml, roles/lnls-ans-role-octave/vars/Debian-jessie.yml, roles/lnls-ans-role-octave/vars/Debian-stretch.yml, roles/lnls-ans-role-octave/vars/Debian-wheezy.yml, roles/lnls-ans-role-octave/vars/Debian.yml, roles/lnls-ans-role-octave/vars/RedHat.yml, roles/lnls-ans-role-octave/vars/Ubuntu-artful.yml, roles/lnls-ans-role-octave/vars/Ubuntu-bionic.yml, roles/lnls-ans-role-octave/vars/Ubuntu-trusty.yml, roles/lnls-ans-role-octave/vars/Ubuntu-xenial.yml, roles/lnls-ans-role-octave/vars/Ubuntu-zesty.yml, tasks-desktops.yml
This is role is simple and just install 2 packages for now, octave and liboctave-dev, but more customizations are likely to occur, such as configuration files and more octave-related packages (graphical frontends, for instance).
=> Pr role octave

roles/lnls-ans-role-epics-mca/Vagrant/README.md, roles/lnls-ans-role-epics-mca/Vagrant/Vagrantfile, roles/lnls-ans-role-epics-mca/Vagrant/hosts, roles/lnls-ans-role-epics-mca/Vagrant/setup.yml, roles/lnls-ans-role-octave/Vagrant/README.md, roles/lnls-ans-role-octave/Vagrant/Vagrantfile, roles/lnls-ans-role-octave/Vagrant/hosts, roles/lnls-ans-role-octave/Vagrant/setup.yml
Add missing Vagrant directories for easy testing roles
=> Pr add vagrant directories

group_vars/all, roles/lnls-ans-role-sirius-apps/defaults/main.yml, tasks-desktops.yml
This repository is used to analyse BPM data, as well as to perform some machine studies.
=> Pr add bpm scripts repo

Makefile, playbook-control-room-desktops-sirius.yml, tasks-desktops-sirius.yml
This playbook only applies packages that are most likely to change.
=> Add faster deploy playbook

playbooks-services/playbook-service-ioc-as-ap.yml, roles/lnls-ans-role-cs-studio/meta/main.yml, roles/lnls-ans-role-desktop-apps/meta/main.yml, roles/lnls-ans-role-epics-mca/meta/main.yml, roles/lnls-ans-role-epics-mca/tasks/clone-install-app.yml, roles/lnls-ans-role-epics/meta/main.yml, roles/lnls-ans-role-octave/tasks/main.yml, roles/lnls-ans-role-phoebus/meta/main.yml, roles/lnls-ans-role-pydm/defaults/main.yml, roles/lnls-ans-role-pydm/meta/main.yml, roles/lnls-ans-role-pydm/molecule/default/playbook.yml, roles/lnls-ans-role-pydm/tasks/setup-pydm.yml, roles/lnls-ans-role-qt/meta/main.yml, roles/lnls-ans-role-sirius-apps/meta/main.yml, roles/lnls-ans-role-sirius-bbb/meta/main.yml, roles/lnls-ans-role-visual-studio-code/molecule/code-only/playbook.yml, roles/lnls-ans-role-visual-studio-code/molecule/default/playbook.yml, roles/lnls-ans-role-visual-studio-code/tasks/install-apt.yml, roles/lnls-ans-role-visual-studio-code/tasks/install-dnf.yml, roles/lnls-ans-role-visual-studio-code/tasks/install-extensions.yml, roles/lnls-ans-role-visual-studio-code/tasks/install-yum.yml, roles/lnls-ans-role-visual-studio-code/tasks/install-zypper.yml, roles/lnls-ans-role-visual-studio-code/tasks/write-settings.yml, roles/lnls-ans-role-zabbix/meta/main.yml
The command executed was:
yamllint -c roles/lnls-ans-role-epics/.yamllint $(find . -iname "*.yml")
And the output:
./roles/lnls-ans-role-visual-studio-code/tasks/install-yum.yml
3:11      warning  truthy value is not quoted  (truthy)
9:11      warning  truthy value is not quoted  (truthy)
16:15     warning  truthy value is not quoted  (truthy)
19:11     warning  truthy value is not quoted  (truthy)
./roles/lnls-ans-role-visual-studio-code/tasks/install-apt.yml
3:11      warning  truthy value is not quoted  (truthy)
15:11     warning  truthy value is not quoted  (truthy)
21:11     warning  truthy value is not quoted  (truthy)
28:11     warning  truthy value is not quoted  (truthy)
./roles/lnls-ans-role-visual-studio-code/tasks/write-settings.yml
3:11      warning  truthy value is not …
=> various: fix yaml lint issues according to yamllint

group_vars/all, roles/lnls-ans-role-python/vars/Debian-buster.yml, roles/lnls-ans-role-python/vars/Debian-stretch.yml, roles/lnls-ans-role-python/vars/Debian.yml, roles/lnls-ans-role-qt/defaults/main.yml, roles/lnls-ans-role-sirius-apps/vars/Debian-buster.yml, roles/lnls-ans-role-sirius-apps/vars/Debian-jessie.yml, roles/lnls-ans-role-sirius-apps/vars/Debian-stretch.yml, roles/lnls-ans-role-sirius-apps/vars/Debian.yml, roles/lnls-ans-role-sirius-apps/vars/RedHat.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-artful.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-bionic.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-trusty.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-utopic.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-vivid.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-wily.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-xenial.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-yakkety.yml, roles/lnls-ans-role-sirius-apps/vars/Ubuntu-zesty.yml
@xresende, @lerwys, I think this PR is ready for revision now!
I have tested in lnls454-linux, lnlsfac-vm1 and lnls557-linux.
=> Update python packages

group_vars/all, hosts
@ito-rafael @carneirofc Can you check if this change is ok for you? It will change /home/con-srv/cons-opis IP server, as well. Is that ok?
=> group_vars/all: change NFS OPI server IP

group_vars/all, roles/lnls-ans-role-nfsclient/tasks/main.yml, roles/lnls-ans-role-nfsclient/tasks/setup-Debian.yml, roles/lnls-ans-role-nfsclient/tasks/setup-RedHat.yml, roles/lnls-ans-role-nfsclient/tasks/setup-packages.yml, roles/lnls-ans-role-nfsserver/defaults/main.yml, roles/lnls-ans-role-nfsserver/tasks/main.yml, roles/lnls-ans-role-nfsserver/tasks/setup-Debian.yml, roles/lnls-ans-role-nfsserver/tasks/setup-RedHat.yml, roles/lnls-ans-role-nfsserver/tasks/setup-packages.yml, roles/lnls-ans-role-nfsserver/templates/exports.j2
Along with general changes, this mainly fixes the nfsserver to export the current directories. There is still the change of updating the NFS server directories to come.
=> Pr fix nfs roles

group_vars/all, roles/lnls-ans-role-network/README.md, roles/lnls-ans-role-network/defaults/main.yml, roles/lnls-ans-role-network/vars/Debian-buster.yml, roles/lnls-ans-role-network/vars/Debian-stretch.yml, roles/lnls-ans-role-network/vars/Debian.yml, roles/lnls-ans-role-network/vars/RedHat.yml, roles/lnls-ans-role-sirius-apps/templates/sirius_apps.sh.j2
=> lnls-ans-role-network: update network-manager related packages

group_vars/all
All new package releases have already been tested in IOCs and HLAs.
=> New Deploy

group_vars/all, roles/lnls-ans-role-desktop-apps/vars/Debian-buster.yml, roles/lnls-ans-role-desktop-apps/vars/Debian-stretch.yml, roles/lnls-ans-role-desktop-apps/vars/Debian.yml
Latex is very useful to make pretty labels and texts in matplotlib figures and it is also an interesting tool for notebooks.
=> Add texlive-full to the list of installed packages.

roles/lnls-ans-role-desktop-apps/templates/vncserver@.service.j2
This should make VNC automatic restart seamless
=> Robustify VNC server restarts

.github/workflows/ansible-lint.yml, README.md
PR to add automatic github action to run ansible-lint for every new commit/branch/PR
=> Pr add ansible lint action

.github/workflows/ansible-lint.yml
This is related to ansible-collections/community.kubernetes#135
=> .github: fix failing ansible-lint by removing overrides

group_vars/all, roles/lnls-ans-role-ntp/templates/ntp.conf.j2
Change NTP clint config: seems to be broken with new version of NTP server.
=> lnls-ans-role-ntp: update script

group_vars/all, group_vars/nfs_servers
Add package `siriushlafac` from the repo www.github.com/lnls-fac/hlafac to the list of `siriushla_apps`.
=> Add siriushlafac

roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-as-di-fpm.desktop, roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-li-di-ict.desktop, roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-si-pu-injsi.desktop, roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-tb-pu-injbo.desktop, roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-ts-di-ict.desktop, roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-ts-pu-ejebo.desktop, roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-scope-ts-pu-injsi.desktop
- add new links to all oscilloscopes, using the correct hostname in connections.
- standardize name of icons for all oscilloscopes.
- use correct hostnames for all oscilloscopes connections.
=> ENH: Improve set of links to Oscilloscopes in Desktop:

roles/lnls-ans-role-ntp/tasks/main.yml
https://github.com/lnls-sirius/lnls-ansible/issues/249
=> tzdata package state set from present to latest

group_vars/all
=> siriushlacon version update

inventories/sirius/group_vars/all
siriushlacon version bump (2.1.1)
=> siriushlacon version bump (2.1.1)

inventories/sirius/group_vars/all
Tag https://github.com/lnls-sirius/pydm-opi/releases/tag/2.2.0
=> Update siriushlacon version

roles/lnls-ans-role-sirius-apps/templates/sirius_apps.sh.j2
This new IP address won't change for at least a few months.
=> Controller of EMA undulator has a new IP address

roles/lnls-ans-role-cs-studio/defaults/main.yml, roles/lnls-ans-role-cs-studio/meta/main.yml, roles/lnls-ans-role-cs-studio/tasks/setup-cs-studio.yml, roles/lnls-ans-role-cs-studio/vars/Debian-bullseye.yml, roles/lnls-ans-role-cs-studio/vars/main.yml
Remove e-mail and beast references;
Add bullseye var file.
=> PR CS-Studio
