lnls-sirius/lnls-ansible

roles/lnls-ans-role-users/tasks/grant-root.yml

Fix sudoers file modification in lnls-ans-role-users to disallow passwordless sudo

lnls-ans-role-users: fix sudoers to disallow passwordless sudo

---

roles/lnls-ans-role-cs-studio/meta/main.yml
roles/lnls-ans-role-desktop-apps/meta/main.yml
roles/lnls-ans-role-epics/meta/main.yml
roles/lnls-ans-role-phoebus/meta/main.yml
roles/lnls-ans-role-pydm/meta/main.yml
roles/lnls-ans-role-qt/meta/main.yml
roles/lnls-ans-role-sirius-apps/meta/main.yml
roles/lnls-ans-role-zabbix/meta/main.yml

Removing the dependencies speed up the running time by a factor of two with a single host already synchronized. 
Instead of removing the dependencies, I tried to import them with a condition which checked if they had already run (like this:
```dependencies:
- { role: 'xcode', when: ansible_os_family == 'Darwin' }
```
), but the result was not as I expected.
Maybe in the future we could study a better way of including dependencies...

Remove dependencies

---

roles/lnls-ans-role-epics/tasks/main.yml
roles/lnls-ans-role-epics/tasks/setup-Debian.yml
roles/lnls-ans-role-epics/vars/Debian-buster.yml
roles/lnls-ans-role-epics/vars/Debian-jessie.yml
roles/lnls-ans-role-epics/vars/Debian-stretch.yml
roles/lnls-ans-role-epics/vars/Debian.yml
roles/lnls-ans-role-epics/vars/Ubuntu-bionic.yml
roles/lnls-ans-role-epics/vars/Ubuntu-trusty.yml
roles/lnls-ans-role-epics/vars/Ubuntu-xenial.yml

so as to allow linac PS iocs to run in any server.

lnls-ans-role-epics: add pcaspy and epics python2 packages

---

ansible.cfg
tasks-desktops-sirius.yml

- added role defines missing *user* variable

playbooks: add users task to tasks-desktops-sirius.yml

---

group_vars/all
roles/lnls-ans-role-network/.flake8
roles/lnls-ans-role-network/.gitignore
roles/lnls-ans-role-network/.yamllint
roles/lnls-ans-role-network/LICENSE
roles/lnls-ans-role-network/README.md
roles/lnls-ans-role-network/Vagrant/README.md
roles/lnls-ans-role-network/Vagrant/Vagrantfile
roles/lnls-ans-role-network/Vagrant/hosts
roles/lnls-ans-role-network/Vagrant/setup.yml
roles/lnls-ans-role-network/defaults/main.yml
roles/lnls-ans-role-network/handlers/main.yml
roles/lnls-ans-role-network/meta/main.yml
roles/lnls-ans-role-network/molecule/default/Dockerfile.j2
roles/lnls-ans-role-network/molecule/default/README.md
roles/lnls-ans-role-network/molecule/default/create.yml
roles/lnls-ans-role-network/molecule/default/destroy.yml
roles/lnls-ans-role-network/molecule/default/molecule.yml
roles/lnls-ans-role-network/molecule/default/playbook.yml
roles/lnls-ans-role-network/molecule/default/tests/test_default.py
roles/lnls-ans-role-network/playbook.yml
roles/lnls-ans-role-network/tasks/main.yml
roles/lnls-ans-role-network/tasks/setup-Debian.yml
roles/lnls-ans-role-network/tasks/setup-RedHat.yml
roles/lnls-ans-role-network/tasks/setup-network.yml
roles/lnls-ans-role-network/vars/Debian-buster.yml
roles/lnls-ans-role-network/vars/Debian-stretch.yml
roles/lnls-ans-role-network/vars/Debian.yml
roles/lnls-ans-role-network/vars/RedHat.yml
tasks-desktops.yml

This PR will fix the issue with multiple DNS by effectively disabling the DNS coming from the TIC VLAN. @edupcoelho had already suggested this approach. I've just created the automation means for that. Be advised that if the interface name is different than `"TIC"`, the role will fail for that host, but you can change the interface name via `defaults/main.yml`
Please, test this role (against your own computer maybe, if it runs NetworkManager) to check if you can reach the names in both our domain and internet/intranet

Pr add role network

---

playbooks-services/playbook-service-ioc-as-ap.yml

Before deploying with this PR merged we should run makefile target `service-ioc-as-ap-stop`!

Update service-ioc-as-ap with new currinfo iocs

---

Makefile_services.mk
group_vars/all
group_vars/con
group_vars/control_room_FBP
group_vars/fac_servers
hosts
playbook-control-room-desktops-sirius.yml
playbook-control-room-desktops.yml
playbooks-services/playbook-service-ioc-tb-ps.yml

so that we can cope with FBP UDCs (TB quads) running with updated BSMP spec while other UDCs (TB dips) running with temporarily deprecated spec.

Prepare configs for parallel FBP siriuspy package

---

roles/lnls-ans-role-repositories/tasks/setup-Debian.yml
tasks-desktops.yml

- install repositories keys first. (workaround abandoned)

Swap tasks in lnls-ans-role-repositories

---

group_vars/control_room_LEGACY

Thanks @lerwys  for pointing out that non-default values for this host group are necessary.

group_vars: fix missing vars in control_room_LEGACY

---

group_vars/all

Updating tags for latest release for pru-serial485 (v1.5.0) and eth-bridge-pru-serial485 (v2.6.0)
@xresende is there any other file to update?

Updating tags for pru-serial485 and eth-bridge

---

group_vars/all

So that deploy works in all debian stretch 9.11-9.13 versions without package downgrade.

group_vars/all: update libdbus version

---

roles/lnls-ans-role-desktop-apps/files/skel/.vnc/xstartup
roles/lnls-ans-role-desktop-apps/files/skel/Desktop/sirius-terminal.desktop

Make sure terminals created e by desktop icon loads environment variables needed by Epics.

Load EPICS Variables in Terminals via VNC

---

.travis.yml

Warnings were:
root: deprecated key sudo (The key `sudo` has no effect anymore.)
root: missing dist, using the default xenial
root: missing os, using the default linux
env: key matrix is an alias for jobs, using jobs

.travis.yml: fix travis config warnings

---

roles/lnls-ans-role-qt/tasks/remove-qt-from-apt.yml

The ansible warning was:
```
TASK [lnls-ans-role-qt : Ensure no Qt system versions are installed] ********************************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name:
"{{ item | regex_replace('=.*$', '') }}"`, please use `name: ['{{ qt_distro_packages }}']` and remove the loop. This feature will be removed in version 2.11. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [dig-testes.abtlus.org.br] => (item=['qt5-default', 'qttools5-dev-tools', 'sip-dev', 'python3-pyqt5.qtsvg', 'libqt5opengl5-dev', 'qt5-qmake', 'qtbase5-dev'])
```
This was …

lnls-ans-role-qt: fix deprecated apt looping action

---

roles/lnls-ans-role-sirius-hlacon/templates/siriushlacon.j2

The previous template was not passing args to the target script.

Pass arguments to script

---

group_vars/all
playbook-desktops.yml

This PR installs pydm-opi repository into a conda environment by using roles `lnls-ans-role-conda` and `lnls-ans-role-sirius-hlacon`

Pr add conda hlacon role to playbook

---

.github/workflows/merge-travis.yml

This was tested on my fork and it seems to be working ok: https://github.com/lerwys/lnls-ansible/runs/1183825269?check_suite_focus=true
The ideia is that this action will merge `master`into `travis-build` automatically every night at midnight, so travis will run our tests

Pr add periodic travis build

---

hosts

Improve comments in `host` that indicate where IOCs run, so that operators can use the file as a reference

hosts: update comment on where FAC IOCs run

---

playbooks/playbook-desktops.yml

The glusterfs role must be dynamically imported.
The roles **lnls-ans-role-glusterfs** and **lnls-ans-role-nfsclient** were moved to `tasks` and are being imported using `include_role`. 
https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse

dynamic imported roles

---

.ci_build.sh

The current molecule setup was not compatible with this script and after the inventory changes the problem became apparent.
I've removed the code because in reality it was not doing anything useful.
```bash
mkdir -p roles/${ROLE}/group_vars && \
cp --verbose inventories/sirius/group_vars/all roles/${ROLE}/group_vars/all && \
```
There are other approaches for this, but they all require several changes throughout the code.
In order for it to work as originally expected we would have to change `../../../../group_vars/` -> `../../group_vars/`, but that would break local molecule executions.
https://github.com/lnls-sirius/lnls-ansible/blob/master/roles/lnls-ans-role-users/molecule/default/molecule.yml#L13
https://github.com/lnls-sirius/lnls-ansible/blob/master/roles/lnls-ans-role-users/molecul …

Fix group_vars location problems due to the current molecule setup

---

roles/lnls-ans-role-repositories/vars/Debian-bullseye.yml

This change will allow the installation of the packages required for lnls-ans-role-sirius-hla role on Debian 11.
Basically, a var file named Debian-bullseye.yml was created for lnls-ans-role-repositories role to include the repositories required for the installation of edm-dev and other tools on Debian 11.

HLA packages on Debian 11

---

roles/lnls-ans-role-ntp/vars/Debian-bullseye.yml

Add Debian-bullseye.yml var file to zabbix role and add bullseye-backports to the list of repositories of Debian Bullseye.

Add Debian-bullseye.yml var file to ntp role

---

roles/lnls-ans-role-conda/meta/main.yml

The conda installation role was tested today on Debian 11 and works perfectly.

conda installation role now is supported on Bullseye

---

inventories/sirius/group_vars/all
roles/lnls-ans-role-nvidia-driver/vars/Debian-stretch.yml
roles/lnls-ans-role-repositories/molecule/default/tests/test_ubuntu_xenial_based.py
roles/lnls-ans-role-repositories/vars/Debian-bullseye.yml
roles/lnls-ans-role-repositories/vars/Debian-stretch.yml
roles/lnls-ans-role-repositories/vars/Ubuntu-xenial.yml

This PR fixes apt source lists generated during deploy for debian stretch hosts. Once debian stretch was moved to `archive` repositories, the new sources are:
```
http://deb.debian.org/debian/ stretch -> http://archive.debian.org/debian/ stretch
http://deb.debian.org/debian/ stretch-updates -> http://archive.debian.org/debian/ stretch-proposed-updates
http://security.debian.org/ stretch/updates -> http://archive.debian.org/debian-security stretch/updates
```
Also, it update vscode version.

Fix deploy
